[build]
  functions = "netlify/functions"

# Schedule functions directly using the schedule property
[[functions]]
  name = "generateRandomNumber"
  schedule = "* * * * *" # Schedule to run every minute
